### ISSUE TITLE
Double-check all functionality works in WSL2

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#145]
Per #37 (especially https://github.com/tighten/takeout/issues/37#issuecomment-701215483) I believe we are completely compatible with WSL2, but I'd love for more WSL2 users to check it out for me.

Thanks to @jonsugar for testing it originally.

**Comment by bandgeekndb** [comment]
## Tested Commands

- [x] `takeout`: Shows usage information and list of available commands
- [x] `takeout list`: Shows containers and status (also tested `--json` flag successfully)
- [x] `takeout enable`: Correctly displays list of services, was able to select mysql, follow prompts, and successfully connect to running MySQL instance
- [x] `takeout enable {service_name} {service_name} ...`: Tested using MySQL and PostgresSQL - Successfully displayed all prompts for both services and started the appropriate services (verified by connecting to both)
    - [x] Given a non-existent service, Takeout successfully returns an error message saying the service is invalid
- [x] `takeout disable`: Correctly displays list of running services, was able to disable one of my previous containers. Was correctly notified about the data volume and shown the docker command to remove that volume (also tested and worked)
- [x] `takeout disable {service_name} {service_name} ...`: Tested with previously started PostgreSQL container - Correctly removed the running container and notified me of the remaining data volume
    - [x] Given a non-existent service (either invalid service or just not started), Takeout successfully returns an error stating it cannot find a Takeout-managed instance of the service
- [x] `takeout start`: Successfully shows menu of stopped containers, allows me to start a container and keeps me in the menu so I can start more containers until I choose to exit the menu
- [x] `takeout start {container_id}`: Starts container (only shows container_id as output)
- [x] `takeout stop`: Successfully shows menu of running containers, allows me to stop a container and keeps me in the menu so I can stop more containers until I choose to exit the menu
- [x] `takeout stop {container_id}`: Stops container (only shows container_id as output)

## Running multiple versions of a dependency
Tested successfully, was able to run different MySQL containers side-by-side without issue as long as I picked sensible options during the enable step (not conflicting ports)

**Of note:** you can't run the same service/version combination twice, even with different ports and data volumes because the containers are named the same. Try to start 2 MySQL containers on 3306 and 3307, both latest, with different data volumes, you'll receive a Docker error about conflicting container names.

## Other Notes
- Messaging isn't clear when starting/stopping containers by ID (this is really a tiny issue, but since messaging is so good elsewhere, it felt out-of-place that messaging wasn't as clear for those commands)

## Conclusion
This is more than ready for primetime in WSL2, I am floored by how easy this makes Docker. Thank you to all who made this a reality, I am incredibly excited to use this going forward!

**Comment by mattstauffer** [comment]
Thank you *so much* for the super thorough test, @bandgeekndb!
