### ISSUE TITLE
Restart docker images after computer/docker restart

### ISSUE THREAD

**Issue by likeadeckofcards** [tighten/takeout#68]
What is the best way to restart docker images after a computer/docker restart?

**Comment by tcampbPPU** [comment]
For traditional docker images spun up should be able to add the additional policy via `$ docker update`
So, for example, list your docker images
```
$ docker ps -a
```

Then obtain the container ID for the image you want to update  and update its policy
```
$ docker update --restart unless-stopped contianer_id
```
Also, make sure you have the setting "Start Docker Desktop when you log in" enabled

**Comment by bandgeekndb** [comment]
Would this make sense to add as a prompt when enabling a service? Ask if the user wants the service restarted with docker/computer and then run this command behind the scenes if it's desired?

**Comment by mattstauffer** [comment]
Hm, I'm also wondering if it's possible to do that without the prompt. Problem is, if we auto restarted *every* container every time, some folks might not like that since they don't want all their containers always running, so we would have to keep track at any given moment of which are started and stopped, and that *also* seems like a pain...

**Comment by josecanhelp** [comment]
This feels like a configuration that Takeout should not be managing. If a container needs to be started, just list the containers and select the ones you need to start. This will be a much smoother process in the node port, btw.
